# Generated by Django 3.2.4 on 2021-06-26 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('idAutor', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Autor')),
                ('nombreAutor', models.CharField(max_length=50, verbose_name='Nombre Autor')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('idNoticia', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Noticia')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('fecha', models.DateField(verbose_name='Fecha publicacion')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrega3.autor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrega3.categoria')),
            ],
        ),
    ]
